language: php

sudo: false

dist: trusty

matrix:
  include:
    - php: 5.5.9
      env: PARSER_VERSION=^2.0
    - php: 5.5.9
      env: PARSER_VERSION=^3.0
    - php: 5.5
      env: PARSER_VERSION=^2.0
    - php: 5.5
      env: PARSER_VERSION=^3.0
    - php: 5.6
      env: PARSER_VERSION=^2.0
    - php: 5.6
      env: PARSER_VERSION=^3.0
    - php: 7.0
      env: PARSER_VERSION=^2.0
    - php: 7.0
      env: PARSER_VERSION=^3.0
    - php: 7.1
      env: PARSER_VERSION=^2.0
    - php: 7.1
      env: PARSER_VERSION=^3.0
    - php: hhvm
      env: PARSER_VERSION=^2.0
    - php: hhvm
      env: PARSER_VERSION=^3.0

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi
  - composer self-update --stable -n
  - composer require "nikic/php-parser:${PARSER_VERSION}" --no-update -n

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
