name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  example:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["7.0", "7.1", "7.2", "7.3", "7.4"]
        phpunit: ["6.5", "7.5", "8.5", "9"]
        exclude:
          - php: "7.0"
            phpunit: "7.5"
          - php: "7.0"
            phpunit: "8.5"
          - php: "7.0"
            phpunit: "9"
          - php: "7.1"
            phpunit: "8.5"
          - php: "7.1"
            phpunit: "9"
          - php: "7.2"
            phpunit: "9"

    name: PHP ${{ matrix.php }}; PHPUnit ${{ matrix.phpunit }}

    steps:
    - uses: actions/checkout@v2
    - name: Pull Docker Image
      run: docker pull registry.gitlab.com/grahamcampbell/php:${{ matrix.php }}
    - name: Select PHPUnit
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint composer registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} require "phpunit/phpunit:{{ matrix.phpunit }}.*" --no-update -n
    - name: Run Composer
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint composer registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} install --no-suggest --prefer-dist -n -o
    - name: Run PHPUnit
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} --coverage-clover build/logs/clover.xml
    - name: Upload Coverage
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint ocular registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} code-coverage:upload --format=php-clover build/logs/clover.xml
